# Netlify deployment configuration

[build]
  command = "python3 convert.py"
  publish = "website-files"

[build.environment]
  PYTHON_VERSION = "3.11"

# Redirect rules for clean URLs
[[redirects]]
  from = "/essays/*"
  to = "/essays/:splat"
  status = 200

# Custom headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
